import streamlit as st
from openai import OpenAI
from pypdf import PdfReader

st.title("📄 Lab 2 - Document Summarizer")
st.write(
    "Upload a PDF document and get a summary generated by GPT. "
    "Choose the summary language and format from the sidebar."
)

client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

SUMMARY_INSTRUCTIONS = {
    "100 words": "Summarize the document in about 100 words.",
    "2 connecting paragraphs": "Summarize the document in 2 connecting paragraphs.",
    "5 bullet points": "Summarize the document in 5 bullet points.",
}

DEFAULT_MODEL = "gpt-5-nano"
ADVANCED_MODELS = ["gpt-3.5-turbo", "gpt-4.1", "gpt-5-chat-latest", "gpt-5-nano"]


def read_pdf(file):
    reader = PdfReader(file)
    return "\n".join(page.extract_text() or "" for page in reader.pages)


with st.sidebar:
    st.header("Summary options")
    language = st.selectbox(
        "Summary language", ["English", "Hindi", "Spanish", "French"]
    )
    summary_type = st.selectbox("Summary type", list(SUMMARY_INSTRUCTIONS.keys()))
    use_advanced_model = st.checkbox("Use advanced model")
    if use_advanced_model:
        model = st.selectbox("Choose a model", ADVANCED_MODELS)
    else:
        model = DEFAULT_MODEL

uploaded_file = st.file_uploader("Upload a document (.pdf)", type=("pdf",))

if uploaded_file:
    document = read_pdf(uploaded_file)

    messages = [
        {
            "role": "user",
            "content": (
                f"Here's a document: {document} \n\n---\n\n "
                f"{SUMMARY_INSTRUCTIONS[summary_type]} Write the summary in {language}."
            ),
        }
    ]

    stream = client.chat.completions.create(
        model=model,
        messages=messages,
        stream=True,
    )

    st.write_stream(stream)
else:
    st.info("Please upload a PDF document to generate a summary.")
